identityCenter:
  name: cloudmar-org-sso
  delegatedAdminAccount: Audit
  identityCenterPermissionSets:
    - name: AdministratorAccess
      description: The Permission Set for AdministratorAccess
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/AdministratorAccess
      sessionDuration: PT12H
    - name: SecurityAdmins
      description: Permission Set for Security Admins
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/ReadOnlyAccess
      sessionDuration: 60
    - name: DevOpsAdmins
      description: Permission Set for DevOps Admins
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/PowerUserAccess
      sessionDuration: 60
        
  identityCenterAssignments:
    - name: AdministratorAccess-Management
      permissionSetName: AdministratorAccess
      principals:
        - type: GROUP
          name: AWS-Management-AdministratorAccess
      deploymentTargets:
        accounts:
          - Management
          - dev
    - name: SecurityAdmins-Management
      permissionSetName: SecurityAdmins
      principals:
        - type: GROUP
          name: AWS-Management-SecurityAdmins
      deploymentTargets:
        organizationalUnits:
          - Root
        excludedAccounts:
          - Audit
          - LogArchive
    - name: DevOpsAdmins-Management
      permissionSetName: DevOpsAdmins
      principals:
        - type: GROUP
          name: AWS-Management-DevOpsAdmins
      deploymentTargets:
        organizationalUnits:
          - Root
        excludedAccounts:
          - Audit
          - LogArchive
